# Generated by Django 4.1.7 on 2023-02-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafes',
            name='rating',
            field=models.FloatField(default=1.1),
        ),
    ]
