# Generated by Django 4.1.7 on 2023-02-17 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_cafes_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafes',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='cafes',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
